### ISSUE TITLE
Empty defaultGameData not handled properly

### ISSUE THREAD

**Issue by piotr-j** [spilgames/spil-android-sdk#4]
Perhaps it just isnt documented yet, but if defaultGameData is just `{}` without some wallet/inventory empty profile is saved in prefs. This causes exceptions on successive app launches as player profile is assumed to not be empty, but it is. `PlayerDataUtil#205` is the failure point, `UserProfile` exists, but walled and currencies are null.

**Comment by sebastian24** [comment]
Should be fixed now. Thanks for reporting that
